#pragma once

// Autogenerated story header for "The Lost Surveyor" adventure (Grayfen Valley)
// Rewritten for the new world structure using declarative endings.
// All objects, items, locations, transitions, requirements, and world
// initialization are statically allocated.

#include "../src/world/world.h"

// --- DESCRIPTIONS -----------------------------------------------------------

static descriptions_t bridge_desc = bufConst(
    2, "The footbridge is collapsed, planks dangling over the ravine.",
    "The bridge is repaired enough to cross safely.");

static descriptions_t trailhead_desc =
    bufConst(1, "The narrow path leading into Grayfen Valley.");
static descriptions_t cabin_desc =
    bufConst(1, "An old hunter's cabin with a broken window.");
static descriptions_t ridge_desc =
    bufConst(1, "A narrow, unstable ridge path.");
static descriptions_t outpost_desc =
    bufConst(1, "The abandoned Grayfen Outpost.");
static descriptions_t lookout_desc =
    bufConst(1, "A small wooden lookout tower behind the outpost.");

static descriptions_t crowbar_desc = bufConst(
    1, "A sturdy metal crowbar—useful for prying things open.");
static descriptions_t rope_desc =
    bufConst(1, "A coiled rope. Strong, dependable.");
static descriptions_t logbook_desc =
    bufConst(1, "The outpost's final logbook.");
static descriptions_t squatter_note_desc =
    bufConst(1, "A note from the squatter asking for help.");

// --- TRANSITIONS ------------------------------------------------------------

static const transition_t BRIDGE_TRANSITION = {
    .action = ACTION_TYPE_USE,
    .from = 0,
    .to = 1,
    .requirements = NULL,
};

static transitions_t BRIDGE_TRANSITIONS = bufConst(1, BRIDGE_TRANSITION);

// --- ITEMS ------------------------------------------------------------------

static item_t ITEM_CROWBAR = {
    .object =
        {
            .name = "crowbar",
            .type = OBJECT_TYPE_ITEM,
            .state = 0,
            .descriptions = &crowbar_desc,
            .transitions = NULL,
        },
    .collectible = true,
    .readable = false,
};

static item_t ITEM_ROPE = {
    .object =
        {
            .name = "rope",
            .type = OBJECT_TYPE_ITEM,
            .state = 0,
            .descriptions = &rope_desc,
            .transitions = NULL,
        },
    .collectible = true,
    .readable = false,
};

static item_t ITEM_LOGBOOK = {
    .object =
        {
            .name = "logbook",
            .type = OBJECT_TYPE_ITEM,
            .state = 0,
            .descriptions = &logbook_desc,
            .transitions = NULL,
        },
    .collectible = true,
    .readable = true,
};

static item_t ITEM_SQUATTER_NOTE = {
    .object =
        {
            .name = "note",
            .type = OBJECT_TYPE_ITEM,
            .state = 0,
            .descriptions = &squatter_note_desc,
            .transitions = NULL,
        },
    .collectible = true,
    .readable = true,
};

// --- LOCATIONS --------------------------------------------------------------
// Per-location static item buffers
static items_t TRAILHEAD_ITEMS = bufConst(0);
static items_t CABIN_ITEMS = bufConst(1, &ITEM_CROWBAR);
static items_t BRIDGE_ITEMS = bufConst(0);
static items_t RIDGE_ITEMS = bufConst(0);
static items_t OUTPOST_ITEMS = bufConst(1, &ITEM_LOGBOOK);
static items_t LOOKOUT_ITEMS = bufConst(1, &ITEM_SQUATTER_NOTE);

static location_t LOC_TRAILHEAD = {
    .object =
        {
            .name = "trailhead",
            .type = OBJECT_TYPE_LOCATION,
            .state = 0,
            .descriptions = &trailhead_desc,
            .transitions = NULL,
        },
    .items = &TRAILHEAD_ITEMS,
    .exits = NULL, // wired later
};

static location_t LOC_CABIN = {
    .object =
        {
            .name = "cabin",
            .type = OBJECT_TYPE_LOCATION,
            .state = 0,
            .descriptions = &cabin_desc,
            .transitions = NULL,
        },
    .items = &CABIN_ITEMS,
    .exits = NULL,
};

static location_t LOC_BRIDGE = {
    .object =
        {
            .name = "bridge",
            .type = OBJECT_TYPE_LOCATION,
            .state = 0,
            .descriptions = &bridge_desc,
            .transitions = &BRIDGE_TRANSITIONS,
        },
    .items = &BRIDGE_ITEMS,
    .exits = NULL,
};

static location_t LOC_RIDGE = {
    .object =
        {
            .name = "ridge",
            .type = OBJECT_TYPE_LOCATION,
            .state = 0,
            .descriptions = &ridge_desc,
            .transitions = NULL,
        },
    .items = &RIDGE_ITEMS,
    .exits = NULL,
};

static location_t LOC_OUTPOST = {
    .object =
        {
            .name = "outpost",
            .type = OBJECT_TYPE_LOCATION,
            .state = 0,
            .descriptions = &outpost_desc,
            .transitions = NULL,
        },
    .items = &OUTPOST_ITEMS,
    .exits = NULL,
};

static location_t LOC_LOOKOUT = {
    .object =
        {
            .name = "lookout",
            .type = OBJECT_TYPE_LOCATION,
            .state = 0,
            .descriptions = &lookout_desc,
            .transitions = NULL,
        },
    .items = &LOOKOUT_ITEMS,
    .exits = NULL,
};

// Exits wiring (static buffers)
static locations_t TRAILHEAD_EXITS =
    bufConst(3, &LOC_CABIN, &LOC_BRIDGE, &LOC_RIDGE);
static locations_t CABIN_EXITS = bufConst(1, &LOC_TRAILHEAD);
static locations_t BRIDGE_EXITS = bufConst(2, &LOC_TRAILHEAD, &LOC_RIDGE);
static locations_t RIDGE_EXITS = bufConst(2, &LOC_TRAILHEAD, &LOC_OUTPOST);
static locations_t OUTPOST_EXITS = bufConst(2, &LOC_RIDGE, &LOC_LOOKOUT);
static locations_t LOOKOUT_EXITS = bufConst(1, &LOC_OUTPOST);

// Attach exits to locations (replace NULL placeholders)
static locations_t *LOC_TRAILHEAD_EXITS_PTR = &TRAILHEAD_EXITS;
static locations_t *LOC_CABIN_EXITS_PTR = &CABIN_EXITS;
static locations_t *LOC_BRIDGE_EXITS_PTR = &BRIDGE_EXITS;
static locations_t *LOC_RIDGE_EXITS_PTR = &RIDGE_EXITS;
static locations_t *LOC_OUTPOST_EXITS_PTR = &OUTPOST_EXITS;
static locations_t *LOC_LOOKOUT_EXITS_PTR = &LOOKOUT_EXITS;

__attribute__((constructor)) static void grayfen_attach_exits(void) {
  LOC_TRAILHEAD.exits = LOC_TRAILHEAD_EXITS_PTR;
  LOC_CABIN.exits = LOC_CABIN_EXITS_PTR;
  LOC_BRIDGE.exits = LOC_BRIDGE_EXITS_PTR;
  LOC_RIDGE.exits = LOC_RIDGE_EXITS_PTR;
  LOC_OUTPOST.exits = LOC_OUTPOST_EXITS_PTR;
  LOC_LOOKOUT.exits = LOC_LOOKOUT_EXITS_PTR;
}

// --- REQUIREMENTS & ENDINGS -------------------------------------------------

// Victory: logbook recovered (inventory contains logbook)
static items_t REQ_LOGBOOK_INV = bufConst(1, &ITEM_LOGBOOK);
static requirements_t REQ_LOGBOOK = {
    .inventory = &REQ_LOGBOOK_INV,
    .items = NULL,
    .locations = NULL,
    .turns = 0,
};
static ending_t ENDING_LOGBOOK = {
    .success = true,
    .reason = "You recovered the logbook and returned safely.",
    .requirements = &REQ_LOGBOOK,
};

// Victory: squatter note found (inventory contains squatter note)
static items_t REQ_NOTE_INV = bufConst(1, &ITEM_SQUATTER_NOTE);
static requirements_t REQ_NOTE = {
    .inventory = &REQ_NOTE_INV,
    .items = NULL,
    .locations = NULL,
    .turns = 0,
};
static ending_t ENDING_NOTE = {
    .success = true,
    .reason = "You discovered the squatter and brought back their message.",
    .requirements = &REQ_NOTE,
};

// Death: nightfall (too many turns) – triggers strictly after 60 turns
static requirements_t REQ_NIGHTFALL = {
    .inventory = NULL,
    .items = NULL,
    .locations = NULL,
    .turns = 61, // matches original condition: turns > 60
};
static ending_t ENDING_NIGHTFALL = {
    .success = false,
    .reason = "Night falls and you are forced to retreat.",
    .requirements = &REQ_NIGHTFALL,
};

// Ordered endings (first satisfied wins)
static endings_t WORLD_ENDINGS =
    bufConst(3, &ENDING_LOGBOOK, &ENDING_NOTE, &ENDING_NIGHTFALL);

// --- WORLD OBJECT COLLECTIONS ----------------------------------------------

static items_t WORLD_ITEMS = bufConst(4, &ITEM_CROWBAR, &ITEM_ROPE,
                                      &ITEM_LOGBOOK, &ITEM_SQUATTER_NOTE);

static items_t INVENTORY = bufInit(8, 0, NULL, NULL, NULL, NULL, NULL, NULL,
                                   NULL, NULL);

static locations_t WORLD_LOCATIONS =
    bufConst(6, &LOC_TRAILHEAD, &LOC_CABIN, &LOC_BRIDGE, &LOC_RIDGE,
             &LOC_OUTPOST, &LOC_LOOKOUT);

// --- WORLD INITIALIZATION --------------------------------------------------

world_t grayfen = {
    .items = &WORLD_ITEMS,
    .locations = &WORLD_LOCATIONS,
    .endings = &WORLD_ENDINGS,
    .turns = 0,
    .inventory = &INVENTORY,
    .location = &LOC_TRAILHEAD,
    .end_game = NULL,
};

world_t *world = &grayfen;