#pragma once

// Autogenerated story header for "The Lost Surveyor" adventure
// All objects, items, locations, transitions, and world initialization
// are statically allocated.

#include "../src/world.h"

static descriptions_t NO_DESCRIPTIONS = bufConst(1, "");
static items_t NO_ITEMS = bufConst(0);

// --- OBJECTS ---------------------------------------------------------------

// State descriptions (no magic, low complexity)
static descriptions_t bridge_state_desc =
    bufConst(2, "The footbridge is collapsed, planks dangling over the ravine.",
             "The bridge is repaired enough to cross safely.");

// Items
static item_t ITEM_CROWBAR = {
    .object =
        {
            .name = "crowbar",
            .type = OBJECT_TYPE_ITEM,
            .current_state = 0,
            .description =
                "A sturdy metal crowbar—useful for prying things open.",
            .state_descriptions = &NO_DESCRIPTIONS,
            .transitions = NULL,
        },
    .collectible = true,
    .readable = false,
};

static item_t ITEM_ROPE = {
    .object =
        {
            .name = "rope",
            .type = OBJECT_TYPE_ITEM,
            .current_state = 0,
            .description = "A coiled rope. Strong, dependable.",
            .state_descriptions = &NO_DESCRIPTIONS,
            .transitions = NULL,
        },
    .collectible = true,
    .readable = false,
};

static item_t ITEM_LOGBOOK = {
    .object =
        {
            .name = "logbook",
            .type = OBJECT_TYPE_ITEM,
            .current_state = 0,
            .description = "The outpost's final logbook.",
            .state_descriptions = &NO_DESCRIPTIONS,
            .transitions = NULL,
        },
    .collectible = true,
    .readable = true,
};

static item_t ITEM_SQUATTER_NOTE = {
    .object =
        {
            .name = "note",
            .type = OBJECT_TYPE_ITEM,
            .current_state = 0,
            .description = "A note from the squatter asking for help.",
            .state_descriptions = &NO_DESCRIPTIONS,
            .transitions = NULL,
        },
    .collectible = true,
    .readable = true,
};

// Bridge transitions
static const transition_t BRIDGE_TRANSITION = {
    .trigger = ACTION_TYPE_USE,
    .from = 0,
    .to = 1,
    .required_items = NULL,
};

static transitions_t BRIDGE_TRANSITIONS = bufConst(1, BRIDGE_TRANSITION);

// Bridge object
static const object_t OBJECT_BRIDGE = {
    .name = "bridge",
    .type = OBJECT_TYPE_LOCATION,
    .current_state = 0,
    .description = "A broken footbridge spanning a deep ravine.",
    .state_descriptions = &bridge_state_desc,
    .transitions = &BRIDGE_TRANSITIONS,
};

// --- LOCATIONS -------------------------------------------------------------

static items_t TRAILHEAD_ITEMS = bufConst(0);
static items_t CABIN_ITEMS_BUF = bufConst(1, &ITEM_CROWBAR);
static items_t OUTPOST_ITEMS_BUF = bufConst(1, &ITEM_LOGBOOK);
static items_t LOOKOUT_ITEMS_BUF = bufConst(1, &ITEM_SQUATTER_NOTE);

static locations_t TRAILHEAD_EXITS;
static locations_t CABIN_EXITS;
static locations_t BRIDGE_EXITS;
static locations_t RIDGE_EXITS;
static locations_t OUTPOST_EXITS;
static locations_t LOOKOUT_EXITS;

// Define location objects first
static location_t LOC_TRAILHEAD = {
    .object =
        {
            .name = "trailhead",
            .type = OBJECT_TYPE_LOCATION,
            .current_state = 0,
            .description = "The narrow path leading into Grayfen Valley.",
            .state_descriptions = &NO_DESCRIPTIONS,
            .transitions = NULL,
        },
    .items = &TRAILHEAD_ITEMS,
    .exits = &TRAILHEAD_EXITS,
};

static location_t LOC_CABIN = {
    .object =
        {
            .name = "cabin",
            .type = OBJECT_TYPE_LOCATION,
            .current_state = 0,
            .description = "An old hunter's cabin with a broken window.",
            .state_descriptions = &NO_DESCRIPTIONS,
            .transitions = {},
        },
    .items = &CABIN_ITEMS_BUF,
    .exits = &CABIN_EXITS,
};

static location_t LOC_BRIDGE = {
    .object = OBJECT_BRIDGE,
    .items = &NO_ITEMS,
    .exits = &BRIDGE_EXITS,
};

static location_t LOC_RIDGE = {
    .object =
        {
            .name = "ridge",
            .type = OBJECT_TYPE_LOCATION,
            .current_state = 0,
            .description = "A narrow, unstable ridge path.",
            .state_descriptions = &NO_DESCRIPTIONS,
            .transitions = {},
        },
    .items = &NO_ITEMS,
    .exits = &RIDGE_EXITS,
};

static location_t LOC_OUTPOST = {
    .object =
        {
            .name = "outpost",
            .type = OBJECT_TYPE_LOCATION,
            .current_state = 0,
            .description = "The abandoned Grayfen Outpost.",
            .state_descriptions = &NO_DESCRIPTIONS,
            .transitions = NULL,
        },
    .items = &OUTPOST_ITEMS_BUF,
    .exits = &OUTPOST_EXITS,
};

static location_t LOC_LOOKOUT = {
    .object =
        {
            .name = "lookout",
            .type = OBJECT_TYPE_LOCATION,
            .current_state = 0,
            .description = "A small wooden lookout tower behind the outpost.",
            .state_descriptions = &NO_DESCRIPTIONS,
            .transitions = NULL,
        },
    .items = &LOOKOUT_ITEMS_BUF,
    .exits = &LOOKOUT_EXITS,
};

// Exits wiring (statically built arrays)
static location_t *OUTPOST_EXITS_BUF[] = {&LOC_RIDGE, &LOC_LOOKOUT};
static location_t *LOOKOUT_EXITS_BUF[] = {&LOC_OUTPOST};

static locations_t TRAILHEAD_EXITS =
    bufConst(3, (struct location_t *)&LOC_CABIN,
             (struct location_t *)&LOC_BRIDGE, (struct location_t *)&LOC_RIDGE);

static locations_t CABIN_EXITS =
    bufConst(1, (struct location_t *)&LOC_TRAILHEAD);

static locations_t BRIDGE_EXITS = bufConst(
    2, (struct location_t *)&LOC_TRAILHEAD, (struct location_t *)&LOC_RIDGE);

static locations_t RIDGE_EXITS = bufConst(
    2, (struct location_t *)&LOC_TRAILHEAD, (struct location_t *)&LOC_OUTPOST);

static locations_t OUTPOST_EXITS = bufConst(2, (struct location_t *)&LOC_RIDGE,
                                            (struct location_t *)&LOC_LOOKOUT);

static locations_t LOOKOUT_EXITS =
    bufConst(1, (struct location_t *)&LOC_OUTPOST);

// --- WORLD DIGEST (VICTORY / DEATH CHECKS) --------------------------------
static game_state_t grayfen_digest(world_t *world) {
  // WIN: logbook collected
  if (itemsFind(world->state.inventory, &ITEM_LOGBOOK) >= 0) {
    world->current_end_game = "You recovered the logbook and returned safely.";
    return GAME_STATE_VICTORY;
  }

  // WIN: squatter note found
  if (itemsFind(world->state.inventory, &ITEM_SQUATTER_NOTE) >= 0) {
    world->current_end_game =
        "You discovered the squatter and brought back their message.";
    return GAME_STATE_VICTORY;
  }

  // LOSE: too many turns
  if (world->state.turns > 60) {
    world->current_end_game = "Night falls and you are forced to retreat.";
    return GAME_STATE_DEAD;
  }

  return GAME_STATE_CONTINUE;
}

// --- WORLD INITIALIZATION --------------------------------------------------
static items_t WORLD_ITEMS =
    bufConst(4, &ITEM_CROWBAR, &ITEM_ROPE, &ITEM_LOGBOOK, &ITEM_SQUATTER_NOTE);

static items_t INVENTORY = bufInit(4, 0, NULL, NULL, NULL, NULL);

static locations_t WORLD_LOCATIONS = bufConst(
    6, (struct location_t *)&LOC_TRAILHEAD, (struct location_t *)&LOC_CABIN,
    (struct location_t *)&LOC_BRIDGE, (struct location_t *)&LOC_RIDGE,
    (struct location_t *)&LOC_OUTPOST, (struct location_t *)&LOC_LOOKOUT);

world_t grayfen = {
    .state =
        {
            .turns = 0,
            .inventory = &INVENTORY,
        },
    .locations = &WORLD_LOCATIONS,
    .items = &WORLD_ITEMS,
    .current_location = &LOC_TRAILHEAD,
    .current_end_game = NULL,
    .digest = grayfen_digest,
};

world_t *world = &grayfen;
