#pragma once

// Autogenerated story header for "The Lost Surveyor" adventure (Grayfen Valley)
// Rewritten for the new world structure using declarative endings.
// All objects, items, locations, transitions, requirements, and world
// initialization are statically allocated.

#include "../../src/world/world.h"

// --- MACROS ----------------------------------------------------------------

#define str(Name, Value) char Name[] = Value
#define dsc(Name, Length, ...)                                                 \
  static descriptions_t Name = bufConst(Length, __VA_ARGS__)

// --- DESCRIPTIONS ----------------------------------------------------------

// Location names
str(loc_trailhead_name, "trailhead");
str(loc_cabin_name, "cabin");
str(loc_bridge_name, "bridge");
str(loc_ridge_name, "ridge");
str(loc_outpost_name, "outpost");
str(loc_lookout_name, "lookout");

// Bridge (multi-state)
str(bridge_desc_0,
    "The footbridge is collapsed, planks dangling over the ravine.");
str(bridge_desc_1, "The bridge is repaired enough to cross safely.");
dsc(bridge_descs, 2, bridge_desc_0, bridge_desc_1);

// Trailhead
str(trailhead_desc_0, "The narrow path leading into Grayfen Valley.");
dsc(trailhead_descs, 1, trailhead_desc_0);

// Cabin
str(cabin_desc_0, "An old hunter's cabin with a broken window.");
dsc(cabin_descs, 1, cabin_desc_0);

// Ridge
str(ridge_desc_0, "A narrow, unstable ridge path.");
dsc(ridge_descs, 1, ridge_desc_0);

// Outpost
str(outpost_desc_0, "The abandoned Grayfen Outpost.");
dsc(outpost_descs, 1, outpost_desc_0);

// Lookout
str(lookout_desc_0, "A small wooden lookout tower behind the outpost.");
dsc(lookout_descs, 1, lookout_desc_0);

// Crowbar
str(item_crowbar_name, "crowbar");
str(item_crowbar_desc_0,
    "A sturdy metal crowbar—useful for prying things open.");
dsc(item_crowbar_descs, 1, item_crowbar_desc_0);

// Rope
str(item_rope_name, "rope");
str(item_rope_desc_0, "A coiled rope. Strong, dependable.");
dsc(item_rope_descs, 1, item_rope_desc_0);

// Logbook
str(item_logbook_name, "logbook");
str(item_logbook_desc_0, "The outpost's final logbook.");
dsc(item_logbook_descs, 1, item_logbook_desc_0);

// Squatter Note
str(item_squatter_note_name, "note");
str(item_squatter_note_desc_0, "A note from the squatter asking for help.");
dsc(item_squatter_note_descs, 1, item_squatter_note_desc_0);

// --- TRANSITIONS ------------------------------------------------------------

static const transition_t BRIDGE_TRANSITION = {
    .action = ACTION_TYPE_USE,
    .from = 0,
    .to = 1,
    .requirements = NULL,
};

static transitions_t BRIDGE_TRANSITIONS = bufConst(1, BRIDGE_TRANSITION);

// --- ITEMS ------------------------------------------------------------------

static item_t ITEM_CROWBAR = {
    .object =
        {
            .name = item_crowbar_name,
            .type = OBJECT_TYPE_ITEM,
            .state = 0,
            .descriptions = &item_crowbar_descs,
            .transitions = NULL,
        },
    .collectible = true,
    .readable = false,
};

static item_t ITEM_ROPE = {
    .object =
        {
            .name = item_rope_name,
            .type = OBJECT_TYPE_ITEM,
            .state = 0,
            .descriptions = &item_rope_descs,
            .transitions = NULL,
        },
    .collectible = true,
    .readable = false,
};

static item_t ITEM_LOGBOOK = {
    .object =
        {
            .name = item_logbook_name,
            .type = OBJECT_TYPE_ITEM,
            .state = 0,
            .descriptions = &item_logbook_descs,
            .transitions = NULL,
        },
    .collectible = true,
    .readable = true,
};

static item_t ITEM_SQUATTER_NOTE = {
    .object =
        {
            .name = item_squatter_note_name,
            .type = OBJECT_TYPE_ITEM,
            .state = 0,
            .descriptions = &item_squatter_note_descs,
            .transitions = NULL,
        },
    .collectible = true,
    .readable = true,
};

// --- LOCATIONS --------------------------------------------------------------
// Per-location static item buffers
static items_t TRAILHEAD_ITEMS = bufConst(0);
static items_t CABIN_ITEMS = bufConst(1, &ITEM_CROWBAR);
static items_t BRIDGE_ITEMS = bufConst(0);
static items_t RIDGE_ITEMS = bufConst(0);
static items_t OUTPOST_ITEMS = bufConst(1, &ITEM_LOGBOOK);
static items_t LOOKOUT_ITEMS = bufConst(1, &ITEM_SQUATTER_NOTE);

static location_t LOC_TRAILHEAD = {
    .object =
        {
            .name = loc_trailhead_name,
            .type = OBJECT_TYPE_LOCATION,
            .state = 0,
            .descriptions = &trailhead_descs,
            .transitions = NULL,
        },
    .items = &TRAILHEAD_ITEMS,
    .exits = NULL, // wired later
};

static location_t LOC_CABIN = {
    .object =
        {
            .name = loc_cabin_name,
            .type = OBJECT_TYPE_LOCATION,
            .state = 0,
            .descriptions = &cabin_descs,
            .transitions = NULL,
        },
    .items = &CABIN_ITEMS,
    .exits = NULL,
};

static location_t LOC_BRIDGE = {
    .object =
        {
            .name = loc_bridge_name,
            .type = OBJECT_TYPE_LOCATION,
            .state = 0,
            .descriptions = &bridge_descs,
            .transitions = &BRIDGE_TRANSITIONS,
        },
    .items = &BRIDGE_ITEMS,
    .exits = NULL,
};

static location_t LOC_RIDGE = {
    .object =
        {
            .name = loc_ridge_name,
            .type = OBJECT_TYPE_LOCATION,
            .state = 0,
            .descriptions = &ridge_descs,
            .transitions = NULL,
        },
    .items = &RIDGE_ITEMS,
    .exits = NULL,
};

static location_t LOC_OUTPOST = {
    .object =
        {
            .name = loc_outpost_name,
            .type = OBJECT_TYPE_LOCATION,
            .state = 0,
            .descriptions = &outpost_descs,
            .transitions = NULL,
        },
    .items = &OUTPOST_ITEMS,
    .exits = NULL,
};

static location_t LOC_LOOKOUT = {
    .object =
        {
            .name = loc_lookout_name,
            .type = OBJECT_TYPE_LOCATION,
            .state = 0,
            .descriptions = &lookout_descs,
            .transitions = NULL,
        },
    .items = &LOOKOUT_ITEMS,
    .exits = NULL,
};

// Exits wiring (static buffers)
static locations_t TRAILHEAD_EXITS =
    bufConst(3, &LOC_CABIN, &LOC_BRIDGE, &LOC_RIDGE);
static locations_t CABIN_EXITS = bufConst(1, &LOC_TRAILHEAD);
static locations_t BRIDGE_EXITS = bufConst(2, &LOC_TRAILHEAD, &LOC_RIDGE);
static locations_t RIDGE_EXITS = bufConst(2, &LOC_TRAILHEAD, &LOC_OUTPOST);
static locations_t OUTPOST_EXITS = bufConst(2, &LOC_RIDGE, &LOC_LOOKOUT);
static locations_t LOOKOUT_EXITS = bufConst(1, &LOC_OUTPOST);

// Attach exits to locations (replace NULL placeholders)
__attribute__((constructor)) static void grayfen_attach_exits(void) {
  LOC_TRAILHEAD.exits = &TRAILHEAD_EXITS;
  LOC_CABIN.exits = &CABIN_EXITS;
  LOC_BRIDGE.exits = &BRIDGE_EXITS;
  LOC_RIDGE.exits = &RIDGE_EXITS;
  LOC_OUTPOST.exits = &OUTPOST_EXITS;
  LOC_LOOKOUT.exits = &LOOKOUT_EXITS;
}

// --- REQUIREMENTS & ENDINGS -------------------------------------------------

// Victory: logbook recovered (inventory contains logbook)
static const requirement_tuple_t REQ_LOGBOOK_INV_TUPLE = {item_logbook_name,
                                                          OBJECT_STATE_ANY};
static requirement_tuples_t REQ_LOGBOOK_INV =
    bufConst(1, REQ_LOGBOOK_INV_TUPLE);
static requirements_t REQ_LOGBOOK = {
    .inventory = &REQ_LOGBOOK_INV,
    .items = NULL,
    .locations = NULL,
    .turns = 0,
};
str(ending_logbook_reason, "You recovered the logbook and returned safely.");
static ending_t ENDING_LOGBOOK = {
    .success = true,
    .reason = ending_logbook_reason,
    .requirements = &REQ_LOGBOOK,
};

// Victory: squatter note found (inventory contains squatter note)
static const requirement_tuple_t REQ_NOTE_INV_TUPLE = {item_squatter_note_name,
                                                       OBJECT_STATE_ANY};
static requirement_tuples_t REQ_NOTE_INV = bufConst(1, REQ_NOTE_INV_TUPLE);
static requirements_t REQ_NOTE = {
    .inventory = &REQ_NOTE_INV,
    .items = NULL,
    .locations = NULL,
    .turns = 0,
};
str(ending_note_reason,
    "You discovered the squatter and brought back their message.");
static ending_t ENDING_NOTE = {
    .success = true,
    .reason = ending_note_reason,
    .requirements = &REQ_NOTE,
};

// Death: nightfall (too many turns) – triggers strictly after 60 turns
static requirements_t REQ_NIGHTFALL = {
    .inventory = NULL,
    .items = NULL,
    .locations = NULL,
    .turns = 61, // matches original condition: turns > 60
};
str(ending_nightfall_reason, "Night falls and you are forced to retreat.");
static ending_t ENDING_NIGHTFALL = {
    .success = false,
    .reason = ending_nightfall_reason,
    .requirements = &REQ_NIGHTFALL,
};

// Ordered endings (first satisfied wins)
static endings_t WORLD_ENDINGS =
    bufConst(3, &ENDING_LOGBOOK, &ENDING_NOTE, &ENDING_NIGHTFALL);

// --- WORLD OBJECT COLLECTIONS ----------------------------------------------

static items_t WORLD_ITEMS =
    bufConst(4, &ITEM_CROWBAR, &ITEM_ROPE, &ITEM_LOGBOOK, &ITEM_SQUATTER_NOTE);

static items_t INVENTORY =
    bufInit(8, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

static locations_t WORLD_LOCATIONS =
    bufConst(6, &LOC_TRAILHEAD, &LOC_CABIN, &LOC_BRIDGE, &LOC_RIDGE,
             &LOC_OUTPOST, &LOC_LOOKOUT);

// --- WORLD INITIALIZATION --------------------------------------------------

world_t grayfen = {
    .items = &WORLD_ITEMS,
    .locations = &WORLD_LOCATIONS,
    .endings = &WORLD_ENDINGS,
    .turns = 0,
    .inventory = &INVENTORY,
    .location = &LOC_TRAILHEAD,
    .end_game = NULL,
};

world_t *world = &grayfen;
