#!/usr/bin/env bun

import Ajv from "../vendor/ajv7.min.js";
import schema from "./story.schema.json";
import path from "node:path";

const help = () => {
  console.error(
    `usage: ${path.basename(process.argv[1])} <path-of-the-story.json>`,
  );
  process.exit(1);
};

const storyPath = process.argv[2];

if (!storyPath) {
  help();
}

const story = await Bun.file(storyPath).json();

const ajv = new Ajv();
const validate = ajv.compile(schema);

console.log(`Validating ${storyPath}...`);
const isValid = validate(story);

if (!isValid) {
  console.error("Invalid story!");
  console.error(validate.errors);
  process.exit(1);
} else {
  console.log(`Validating ${storyPath}... OK`);
}
